Resources:
  CreateGameSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateGameSession
      CodeUri: lambda/createGameSession/
      Handler: app.handler
      Runtime: nodejs18.x
      Events:
        CreateGameAPI:
          Type: Api
          Properties:
            Path: /create
            Method: POST

  JoinGameSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: JoinGameSession
      CodeUri: lambda/joinGameSession/
      Handler: app.handler
      Runtime: nodejs18.x
      Events:
        JoinGameAPI:
          Type: Api
          Properties:
            Path: /join
            Method: POST

  StartGameSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StartGameSession
      CodeUri: lambda/startGameSession/
      Handler: app.handler
      Runtime: nodejs18.x
      Events:
        StartGameAPI:
          Type: Api
          Properties:
            Path: /start
            Method: POST

  InitJudgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: InitJudge
      CodeUri: lambda/initJudge/
      Handler: app.handler
      Runtime: nodejs18.x
      Events:
        InitJudgeAPI:
          Type: Api
          Properties:
            Path: /init-judge
            Method: POST

  RotateJudgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RotateJudge
      CodeUri: lambda/rotateJudge/
      Handler: app.handler
      Runtime: nodejs18.x
      Events:
        RotateJudgeAPI:
          Type: Api
          Properties:
            Path: /rotate-judge
            Method: POST

  StartRoundFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StartRound
      CodeUri: lambda/startRound/
      Handler: app.handler
      Runtime: nodejs18.x
      Events:
        StartRoundAPI:
          Type: Api
          Properties:
            Path: /start-round
            Method: POST

  DrawCardsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DrawCards
      CodeUri: lambda/drawCards/
      Handler: app.handler
      Runtime: nodejs18.x
      Description: Assigns unique white cards to a player up to a hand of 7
      MemorySize: 128
      Timeout: 10
      Events:
        DrawCardsAPI:
          Type: Api
          Properties:
            Path: /draw-cards
            Method: POST

  SubmitCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SubmitCard
      CodeUri: lambda/submitCard/
      Handler: app.handler
      Runtime: nodejs18.x
      Events:
        SubmitCardAPI:
          Type: Api
          Properties:
            Path: /submit-card
            Method: POST

  GetSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetSession
      CodeUri: lambda/getSession/
      Handler: app.handler
      Runtime: nodejs18.x
      Events:
        GetSessionAPI:
          Type: Api
          Properties:
            Path: /session/{sessionId}
            Method: GET

  PickWinnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PickWinner
      CodeUri: lambda/pickWinner/
      Handler: app.handler
      Runtime: nodejs18.x
      Events:
        PickWinnerAPI:
          Type: Api
          Properties:
            Path: /pick-winner
            Method: POST





