Resources:
  CreateGameSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateGameSession
      CodeUri: lambda/createGameSession/   # <- this folder must contain app.js
      Handler: app.handler          # <- matches file: "app.js" and function: "handler"
      Runtime: nodejs18.x
      Events:
        CreateGameAPI:
          Type: Api
          Properties:
            Path: /create
            Method: GET
